Repository doctrine/rst-parser, pull requests merged in 2018-11, with the labels that each got.

#26 Toc tree with globs adds non *.rst files to toc tree
  lib/Directives/Toctree.php
  tests/BuilderIncludeTest.php
  tests/builder-include/.gitignore
  tests/builder-include/input/file.rst
  tests/builder-include/input/include.rst.inc
  tests/builder-include/input/index.rst
Labels: Bug

#27 Bug with globPattern starting with a slash
  lib/Directives/Toctree.php
  tests/builder-toctree-glob/input/subdir/toctree.rst
  tests/builder-toctree-glob/output/subdir/toctree.html
Labels: Bug

#23 tests case for links absolute / relative to files
  lib/Builder.php
  lib/Builder/Copier.php
  lib/Builder/Documents.php
  lib/Builder/Hooks.php
  lib/Builder/ParseQueue.php
  lib/Builder/ParseQueueProcessor.php
  lib/Builder/Scanner.php
  lib/Builder/State.php
  lib/Directives/Toctree.php
  lib/Environment.php
  lib/UrlGenerator.php
  tests/Builder/CopierTest.php
  tests/Builder/DocumentsTest.php
  tests/Builder/HooksTest.php
  tests/Builder/ParseQueueProcessorTest.php
  tests/Builder/ParseQueueTest.php
  tests/Builder/ScannerTest.php
  tests/BuilderIncludeTest.php
  tests/BuilderTest.php
  tests/BuilderTocTreeGlobTest.php
  tests/EnvironmentTest.php
  tests/RefInsideDirective/BuilderTest.php
  tests/UrlGeneratorTest.php
  tests/builder-fixtures/.gitignore
  tests/builder-fixtures/input/another.rst
  tests/builder-fixtures/input/file.txt
  tests/builder-fixtures/input/index.rst
  tests/builder-fixtures/input/introduction.rst
  tests/builder-fixtures/input/subdir/file.rst
  tests/builder-fixtures/input/subdir/include.rst.inc
  tests/builder-fixtures/input/subdir/index.rst
  tests/builder-fixtures/input/subdir/toc.rst
  tests/builder-fixtures/input/subdirective.rst
  tests/builder-fixtures/input/toc-glob.rst
  tests/builder/input/subdir/toc.rst
Labels: Bug

#28 Refactor toctree glob code
  lib/Directives/Toctree.php
  lib/GlobSearcher.php
  lib/ToctreeBuilder.php
  tests/BuilderTest.php
  tests/GlobSearcherTest.php
  tests/ToctreeBuilderTest.php
  tests/builder-fixtures/input/toc-glob.rst
Labels: Bug

#29 Fix TocNode html and maxdepth option.
  lib/HTML/Nodes/TocNode.php
  tests/BaseBuilderTest.php
  tests/BuilderIncludeTest.php
  tests/BuilderTest.php
  tests/BuilderTocTreeGlobTest.php
  tests/BuilderTocTreeTest.php
  tests/GlobSearcherTest.php
  tests/builder-toctree-glob/input/index.rst
  tests/builder-toctree-glob/output/index.html
  tests/builder-toctree/input/index.rst
  tests/builder-toctree/input/not-parsed/file.rst
  tests/builder-toctree/input/subdir/toctree.rst
  tests/builder-toctree/output/index.html
  tests/builder-toctree/output/subdir/toctree.html
Labels: Bug

#31 Cleanup of ParseQueueProcessor
  lib/Builder/ParseQueueProcessor.php
  lib/Builder/Scanner.php
  lib/Directives/RedirectionTitle.php
  lib/Kernel.php
  tests/Builder/ScannerTest.php
  tests/BuilderTest.php
  tests/HTMLTest.php
  tests/builder-fixtures/input/another.rst
  tests/builder-fixtures/input/index.rst
  tests/html/reference-directive.rst
Labels: Improvement

#32 Trigger error when an unresolved reference is encountered.
  lib/Builder.php
  lib/Builder/Documents.php
  lib/Builder/ParseQueueProcessor.php
  lib/Builder/Scanner.php
  lib/Document.php
  lib/Environment.php
  lib/References/InvalidReference.php
  lib/References/Resolver.php
  tests/Builder/DocumentsTest.php
  tests/BuilderInvalidReferenceTest.php
  tests/References/ResolverTest.php
  tests/builder-invalid-reference/input/index.rst
  tests/builder-invalid-reference/input/reference.rst
Labels: Enhancement

#33 Base url functionality.
  .gitignore
  lib/Builder.php
  lib/Builder/ParseQueueProcessor.php
  lib/Configuration.php
  lib/Environment.php
  lib/HTML/Nodes/TocNode.php
  lib/HTML/Span.php
  lib/Span.php
  lib/UrlGenerator.php
  tests/BaseBuilderTest.php
  tests/BuilderUrlTest.php
  tests/ConfigurationTest.php
  tests/HTML/SpanTest.php
  tests/UrlGeneratorTest.php
  tests/builder-fixtures/.gitignore
  tests/builder-include/.gitignore
  tests/builder-toctree/output/index.html
  tests/builder-toctree/output/subdir/toctree.html
  tests/builder-url/input/index.rst
  tests/builder-url/input/subdir/file.rst
  tests/builder-url/input/subdir/index.rst
Labels: Enhancement

#40 Allow ability to control when base url gets used.
  lib/Configuration.php
  lib/Environment.php
  lib/UrlGenerator.php
  tests/BuilderUrlTest.php
  tests/ConfigurationTest.php
  tests/UrlGeneratorTest.php
Labels: Enhancement

#39 Convert standalone URIs and email addresses to links
  lib/Span.php
  tests/HTMLTest.php
  tests/html/links.rst
  tests/html/standalone-email-addresses.rst
  tests/html/standalone-hyperlinks.rst
Labels: Enhancement

#34 Add support for definition lists.
  lib/DefaultNodeFactory.php
  lib/HTML/Kernel.php
  lib/HTML/Nodes/DefinitionListNode.php
  lib/NodeFactory.php
  lib/NodeTypes.php
  lib/Nodes/DefinitionListNode.php
  lib/Parser/DefinitionList.php
  lib/Parser/DefinitionListTerm.php
  lib/Parser/DocumentParser.php
  lib/Parser/LineChecker.php
  lib/Parser/LineDataParser.php
  lib/Parser/Lines.php
  lib/Parser/State.php
  tests/Parser/LineCheckerTest.php
  tests/ParserTest.php
  tests/files/definition-list.rst
Labels: Enhancement

#43 Add ability to completely ignore invalid references.
  lib/Builder.php
  lib/Builder/Documents.php
  lib/Configuration.php
  lib/References/Resolver.php
  tests/Builder/DocumentsTest.php
  tests/BuilderInvalidReferenceTest.php
  tests/ConfigurationTest.php
  tests/References/ResolverTest.php
Labels: Enhancement

#44 Update docs to show new configuration options.
  docs/en/index.rst
Labels: Documentation

#48 Titles should be references
  lib/Environment.php
  lib/MetaEntry.php
  lib/Renderers/SpanNodeRenderer.php
  tests/Builder/BuilderTest.php
  tests/Builder/input/another.rst
Labels: Enhancement

#49 Fix issue when a link is on multiple lines.
  lib/Renderers/SpanNodeRenderer.php
  lib/Span/SpanProcessor.php
  tests/HTML/HTMLTest.php
  tests/HTML/files/links.rst
Labels: Enhancement

#52 Reorganize classes in the root folder.
  docs/en/index.rst
  lib/Builder.php
  lib/Builder/Documents.php
  lib/Builder/ParseQueueProcessor.php
  lib/Builder/Scanner.php
  lib/Configuration.php
  lib/Directives/CodeBlock.php
  lib/Directives/Directive.php
  lib/Directives/Dummy.php
  lib/Directives/Raw.php
  lib/Directives/Replace.php
  lib/Directives/SubDirective.php
  lib/Directives/Toctree.php
  lib/Environment.php
  lib/Formats/Format.php
  lib/Formats/InternalFormat.php
  lib/HTML/Directives/Div.php
  lib/HTML/Directives/Figure.php
  lib/HTML/Directives/Image.php
  lib/HTML/Directives/Meta.php
  lib/HTML/Directives/Stylesheet.php
  lib/HTML/Directives/Title.php
  lib/HTML/Directives/Url.php
  lib/HTML/Directives/Wrap.php
  lib/HTML/HTMLFormat.php
  lib/Kernel.php
  lib/LaTeX/Directives/Image.php
  lib/LaTeX/Directives/LaTeXMain.php
  lib/LaTeX/Directives/Meta.php
  lib/LaTeX/Directives/Stylesheet.php
  lib/LaTeX/Directives/Title.php
  lib/LaTeX/Directives/Url.php
  lib/LaTeX/Directives/Wrap.php
  lib/LaTeX/LaTeXFormat.php
  lib/Meta/MetaEntry.php
  lib/Meta/Metas.php
  lib/NodeFactory/DefaultNodeFactory.php
  lib/NodeFactory/NodeFactory.php
  lib/NodeFactory/NodeInstantiator.php
  lib/Nodes/NodeTypes.php
  lib/Parser.php
  lib/Parser/DocumentParser.php
  lib/References/Doc.php
  lib/References/Reference.php
  lib/References/Resolver.php
  lib/Toc/GlobSearcher.php
  lib/Toc/ToctreeBuilder.php
  tests/Builder/DocumentsTest.php
  tests/Builder/ParseQueueProcessorTest.php
  tests/Builder/ScannerTest.php
  tests/DefaultNodeFactoryTest.php
  tests/GlobSearcherTest.php
  tests/MetasTest.php
  tests/NodeInstantiatorTest.php
  tests/RefInsideDirective/VersionAddedDirective.php
  tests/References/ResolverTest.php
  tests/ToctreeBuilderTest.php
Labels: Improvement

#53 Replace hardcoded html with twig templates.
  lib/Environment.php
  lib/Nodes/DocumentNode.php
  lib/Templates/default/html/favicon.html.twig
  lib/Templates/default/html/javascript.html.twig
  lib/Templates/default/html/stylesheet-link.html.twig
Labels: Enhancement

#54 Use doctrine/event-manager for event system.
  composer.json
  composer.lock
  docs/en/index.rst
  lib/Builder.php
  lib/Builder/Hooks.php
  lib/Builder/ParseQueueProcessor.php
  lib/Configuration.php
  lib/Event/BuildEvent.php
  lib/Event/PostBuildRenderEvent.php
  lib/Event/PostNodeCreateEvent.php
  lib/Event/PostNodeRenderEvent.php
  lib/Event/PostParseDocumentEvent.php
  lib/Event/PreBuildParseEvent.php
  lib/Event/PreBuildRenderEvent.php
  lib/Event/PreBuildScanEvent.php
  lib/Event/PreNodeRenderEvent.php
  lib/Event/PreParseDocumentEvent.php
  lib/NodeFactory/DefaultNodeFactory.php
  lib/NodeFactory/NodeInstantiator.php
  lib/Nodes/Node.php
  lib/Parser.php
  lib/Parser/DocumentParser.php
  lib/Renderers/RenderedNode.php
  tests/Builder/HooksTest.php
  tests/Builder/ParseQueueProcessorTest.php
  tests/DefaultNodeFactoryTest.php
Labels: Enhancement, WIP

#61 add failing test for links when name contains "::"
  lib/Parser/DocumentParser.php
  lib/Parser/LineChecker.php
  tests/HTML/HTMLTest.php
  tests/HTML/files/link-with-special-char.rst
  tests/Parser/LineCheckerTest.php
  tests/Parser/LineDataParserTest.php
Labels: Bug

#65 Add support for .. class:: directive.
  lib/Directives/Directive.php
  lib/HTML/Directives/ClassDirective.php
  lib/HTML/HTMLFormat.php
  lib/HTML/Renderers/CodeNodeRenderer.php
  lib/HTML/Renderers/DefinitionListNodeRenderer.php
  lib/HTML/Renderers/ListRenderer.php
  lib/HTML/Renderers/TableNodeRenderer.php
  lib/LaTeX/LaTeXFormat.php
  lib/LaTeX/Renderers/CodeNodeRenderer.php
  lib/LaTeX/Renderers/ListRenderer.php
  lib/Nodes/Node.php
  lib/Templates/default/html/code.html.twig
  lib/Templates/default/html/definition-list.html.twig
  lib/Templates/default/html/list.html.twig
  lib/Templates/default/html/paragraph.html.twig
  lib/Templates/default/html/quote.html.twig
  lib/Templates/default/html/table.html.twig
  lib/Templates/default/tex/code.tex.twig
  tests/HTML/HTMLTest.php
  tests/HTML/files/class-directive.rst
Labels: Enhancement

#64 Wrap each section with a div.
  lib/Configuration.php
  lib/HTML/HTMLFormat.php
  lib/HTML/Renderers/SectionBeginNodeRenderer.php
  lib/HTML/Renderers/SectionEndNodeRenderer.php
  lib/HTML/Renderers/TitleNodeRenderer.php
  lib/NodeFactory/DefaultNodeFactory.php
  lib/NodeFactory/NodeFactory.php
  lib/Nodes/NodeTypes.php
  lib/Nodes/SectionBeginNode.php
  lib/Nodes/SectionEndNode.php
  lib/Nodes/TitleNode.php
  lib/Parser/DocumentParser.php
  lib/Templates/TwigTemplateRenderer.php
  lib/Templates/default/html/header-title.html.twig
  lib/Templates/default/html/section-begin.html.twig
  lib/Templates/default/html/section-end.html.twig
  tests/HTML/HTMLTest.php
  tests/HTML/files/titles.rst
  tests/LaTeX/LaTeXTest.php
  tests/Parser/ParserTest.php
Labels: Enhancement

#59 Literal nested inside a directive is not parsed as code
  lib/Parser/DocumentParser.php
  tests/LiteralNestedInDirective/BuilderTest.php
  tests/LiteralNestedInDirective/TipDirective.php
  tests/LiteralNestedInDirective/input/index.rst
Labels: Bug

#66 Reorganize the rst parser docs.
  docs/en/attribution.rst
  docs/en/builder.rst
  docs/en/configuration.rst
  docs/en/custom-directives.rst
  docs/en/customizing-rendering.rst
  docs/en/events.rst
  docs/en/formats.rst
  docs/en/index.rst
  docs/en/sidebar.rst
  docs/en/themes.rst
Labels: Documentation, WIP

#68 Fix issue with sections not being nested properly inside of each other.
  lib/Parser/DocumentParser.php
  tests/HTML/HTMLTest.php
  tests/HTML/files/section-nesting.rst
  tests/Parser/ParserTest.php
Labels: Bug

#70 Add feature to allow the final document html to be indented.
  docs/en/configuration.rst
  lib/Configuration.php
  lib/HTML/Renderers/DocumentNodeRenderer.php
  lib/Nodes/DocumentNode.php
  tests/HTML/IndentHTMLTest.php
Labels: Enhancement
